export const SET_CURRENT_SLIDE_INDEX = 'SET_CURRENT_SLIDE_INDEX'

export const UPDATE_CARD_INFO = 'UPDATE_CARD_INFO'

export const SET_CALCULATOR_DATA = 'SET_CALCULATOR_DATA'

export const TOGGLE_CALCULATOR_VIEW = 'TOGGLE_CALCULATOR_VIEW'