export const SET_CURRENT_SLIDE_INDEX = 'SET_CURRENT_SLIDE_INDEX'

export const UPDATE_CARD_INFO = 'UPDATE_CARD_INFO'

export const TOGGLE_CALCULATOR_VIEW_ON = 'TOGGLE_CALCULATOR_VIEW_ON'
export const TOGGLE_CALCULATOR_VIEW_OFF = 'TOGGLE_CALCULATOR_VIEW_OFF'
export const CALCULATOR_CARD_DATA_SET = 'CALCULATOR_CARD_DATA_SET'